[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
verbosity = 2
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }
gas_reports = ["*"]
gas_reports_ignore = ["MockERC20", "MockToken", "MockPyth"]
rpc_url = "base_sepolia"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 15 }

[profile.lite]
optimizer = false
fuzz = { runs = 10 }
invariant = { runs = 10, depth = 5 }

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
base-sepolia = { key = "${BASESCAN_API_KEY}" }

